# Generated by Django 4.1.3 on 2022-12-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_bookinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn" target="_blank" >ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
